name: javascript-build

on:
  push:
    paths:
      - 'javascript/**'
      - '.github/workflows/nodejs.yml'
    branches:
      - master

  # Run build for any PR
  pull_request:
    paths:
      - 'javascript/**'
      - '.github/workflows/nodejs.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      working-directory: javascript
      run: |
        npm ci
        npm run lint
        npm run build
        npm test
      env:
        CI: true
